[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.182", features = ["derive"] }
serde_json = "1.0.102"
dirs = "6.0.0"
rand = "0.9.2"
argon2 = "0.5.3"
aes-gcm = "0.10.1"
aes = "0.8.2"
zeroize = "1.6.0"
