name: Build Desktop App - Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: desktop/package-lock.json
    
    - name: Install dependencies
      run: |
        cd desktop
        npm ci
    
    - name: Build frontend
      run: |
        cd desktop
        npm run build
    
    - name: Install Tauri CLI
      run: |
        cd desktop
        npm install -g @tauri-apps/cli@latest
    
    - name: Build Tauri app
      run: |
        cd desktop
        echo "Building for Linux x86_64..."
        npm run tauri build -- --target x86_64-unknown-linux-gnu
        echo "Build completed, checking output directory..."
        find . -name "*.tar.gz" -o -name "*.deb" -o -name "*.rpm" | head -10
        echo "Checking bundle directory structure..."
        find desktop/src-tauri/target/ -type d -name "bundle" | head -5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create archive
      run: |
        cd desktop/src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/
        tar -czf ../../../../../../passman-linux.tar.gz passman
        cd ../../../../../
        ls -la passman-linux.tar.gz
    
    - name: Generate checksum
      run: |
        shasum -a 256 passman-linux.tar.gz > passman-linux.tar.gz.sha256
        cat passman-linux.tar.gz.sha256
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: passman-linux.tar.gz
        path: passman-linux.tar.gz
    
    - name: Upload checksum
      uses: actions/upload-artifact@v4
      with:
        name: passman-linux.tar.gz.sha256
        path: passman-linux.tar.gz.sha256
