name: Build CLI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: passman-cli-linux.tar.gz
            platform: linux
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: passman-cli-macos.tar.gz
            platform: macos
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: passman-cli-macos-arm64.tar.gz
            platform: macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: passman-cli-windows.zip
            platform: windows

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build CLI
      run: |
        cargo build --release --target ${{ matrix.target }} --bin passman
    
    - name: Create archive (Linux/macOS)
      if: matrix.platform != 'windows'
      run: |
        mkdir -p passman-cli
        cp target/${{ matrix.target }}/release/passman passman-cli/
        chmod +x passman-cli/passman
        tar -czf ${{ matrix.artifact }} passman-cli/
        ls -la ${{ matrix.artifact }}
    
    - name: Create archive (Windows)
      if: matrix.platform == 'windows'
      run: |
        mkdir -p passman-cli
        cp target/${{ matrix.target }}/release/passman.exe passman-cli/
        powershell Compress-Archive -Path passman-cli -DestinationPath ${{ matrix.artifact }}
        ls -la ${{ matrix.artifact }}
    
    - name: Generate checksum
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          certutil -hashfile ${{ matrix.artifact }} SHA256 > ${{ matrix.artifact }}.sha256
        else
          shasum -a 256 ${{ matrix.artifact }} > ${{ matrix.artifact }}.sha256
        fi
        cat ${{ matrix.artifact }}.sha256
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.artifact }}
    
    - name: Upload checksum
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}.sha256
        path: ${{ matrix.artifact }}.sha256
