name: Build Desktop App - macOS

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-x86_64:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Install system dependencies
      run: |
        echo "Installing macOS build dependencies..."
        # Install Xcode command line tools if not present
        xcode-select --install || true
        # Install additional tools that might be needed
        brew install --quiet pkg-config
        echo "macOS dependencies installed"
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: desktop/package-lock.json
    
    - name: Install dependencies
      run: |
        cd desktop
        npm ci
    
    - name: Build frontend
      run: |
        cd desktop
        npm run build
    
    - name: Install Tauri CLI
      run: |
        cd desktop
        npm install -g @tauri-apps/cli@latest
    
    - name: Build Tauri app (x86_64)
      run: |
        cd desktop
        echo "Building for macOS x86_64..."
        npm run tauri build -- --target x86_64-apple-darwin
        echo "Build completed, checking output directory..."
        find . -name "*.dmg" -o -name "*.app" | head -10
        echo "Checking bundle directory structure..."
        find desktop/src-tauri/target/ -type d -name "bundle" | head -5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create archive (x86_64)
      run: |
        echo "Checking if Tauri build succeeded..."
        if [ ! -d "desktop/src-tauri/target/x86_64-apple-darwin/release/" ]; then
          echo "ERROR: Tauri build failed - no release directory found"
          echo "Contents of desktop/src-tauri/target/:"
          ls -la desktop/src-tauri/target/ || echo "Target directory does not exist"
          exit 1
        fi
        
        echo "Looking for bundle directory..."
        if [ -d "desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/" ]; then
          echo "Found DMG directory, copying files..."
          cd desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/
          cp *.dmg ../../../../../../passman-macos.tar.gz
          cd ../../../../../../
        else
          echo "DMG directory not found, checking for other bundle formats..."
          find desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/ -name "*.dmg" -exec cp {} passman-macos.tar.gz \;
          if [ ! -f "passman-macos.tar.gz" ]; then
            echo "ERROR: No DMG file found after build"
            echo "Contents of bundle directory:"
            find desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/ -type f | head -10
            exit 1
          fi
        fi
        ls -la passman-macos.tar.gz
    
    - name: Generate checksum (x86_64)
      run: |
        shasum -a 256 passman-macos.tar.gz > passman-macos.tar.gz.sha256
        cat passman-macos.tar.gz.sha256
    
    - name: Upload artifacts (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: passman-macos.tar.gz
        path: passman-macos.tar.gz
    
    - name: Upload checksum (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: passman-macos.tar.gz.sha256
        path: passman-macos.tar.gz.sha256

  build-arm64:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Install system dependencies
      run: |
        echo "Installing macOS build dependencies..."
        # Install Xcode command line tools if not present
        xcode-select --install || true
        # Install additional tools that might be needed
        brew install --quiet pkg-config
        echo "macOS dependencies installed"
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: desktop/package-lock.json
    
    - name: Install dependencies
      run: |
        cd desktop
        npm ci
    
    - name: Build frontend
      run: |
        cd desktop
        npm run build
    
    - name: Install Tauri CLI
      run: |
        cd desktop
        npm install -g @tauri-apps/cli@latest
    
    - name: Build Tauri app (ARM64)
      run: |
        cd desktop
        echo "Building for macOS ARM64..."
        npm run tauri build -- --target aarch64-apple-darwin
        echo "Build completed, checking output directory..."
        find . -name "*.dmg" -o -name "*.app" | head -10
        echo "Checking bundle directory structure..."
        find desktop/src-tauri/target/ -type d -name "bundle" | head -5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create archive (ARM64)
      run: |
        echo "Checking if Tauri build succeeded..."
        if [ ! -d "desktop/src-tauri/target/aarch64-apple-darwin/release/" ]; then
          echo "ERROR: Tauri build failed - no release directory found"
          echo "Contents of desktop/src-tauri/target/:"
          ls -la desktop/src-tauri/target/ || echo "Target directory does not exist"
          exit 1
        fi
        
        echo "Looking for bundle directory..."
        if [ -d "desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/" ]; then
          echo "Found DMG directory, copying files..."
          cd desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/
          cp *.dmg ../../../../../../passman-macos-arm64.tar.gz
          cd ../../../../../../
        else
          echo "DMG directory not found, checking for other bundle formats..."
          find desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/ -name "*.dmg" -exec cp {} passman-macos-arm64.tar.gz \;
          if [ ! -f "passman-macos-arm64.tar.gz" ]; then
            echo "ERROR: No DMG file found after build"
            echo "Contents of bundle directory:"
            find desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/ -type f | head -10
            exit 1
          fi
        fi
        ls -la passman-macos-arm64.tar.gz
    
    - name: Generate checksum (ARM64)
      run: |
        shasum -a 256 passman-macos-arm64.tar.gz > passman-macos-arm64.tar.gz.sha256
        cat passman-macos-arm64.tar.gz.sha256
    
    - name: Upload artifacts (ARM64)
      uses: actions/upload-artifact@v4
      with:
        name: passman-macos-arm64.tar.gz
        path: passman-macos-arm64.tar.gz
    
    - name: Upload checksum (ARM64)
      uses: actions/upload-artifact@v4
      with:
        name: passman-macos-arm64.tar.gz.sha256
        path: passman-macos-arm64.tar.gz.sha256
