name: Build Desktop App - Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Install system dependencies
      run: |
        # Windows uses system WebView2, no additional dependencies needed
        echo "Windows uses system WebView2, no additional dependencies required"
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: desktop/package-lock.json
    
    - name: Install dependencies
      run: |
        cd desktop
        npm ci
    
    - name: Build frontend
      run: |
        cd desktop
        npm run build
    
    - name: Install Tauri CLI
      run: |
        cd desktop
        npm install -g @tauri-apps/cli@latest
    
    - name: Build Tauri app
      run: |
        cd desktop
        echo "Building for Windows x86_64..."
        npm run tauri build -- --target x86_64-pc-windows-msvc
        echo "Build completed, checking output directory..."
        find . -name "*.exe" -o -name "*.msi" | head -10
        echo "Checking bundle directory structure..."
        find desktop/src-tauri/target/ -type d -name "bundle" | head -5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create archive
      run: |
        cd target/x86_64-pc-windows-msvc/release/bundle/msi/
        copy *.msi ../../../../../passman-windows.exe
        cd ../../../../../
        dir passman-windows.exe
    
    - name: Generate checksum
      run: |
        certutil -hashfile passman-windows.exe SHA256 > passman-windows.exe.sha256
        type passman-windows.exe.sha256
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: passman-windows.exe
        path: passman-windows.exe
    
    - name: Upload checksum
      uses: actions/upload-artifact@v4
      with:
        name: passman-windows.exe.sha256
        path: passman-windows.exe.sha256
