name: Create Release

on:
  workflow_run:
    workflows: ["Build Desktop App", "Build CLI"]
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Desktop Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: passman-*
        merge-multiple: true
        path: ./artifacts
    
    - name: Download CLI Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: passman-cli-*
        merge-multiple: true
        path: ./artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
